name: Release Application

on:
  workflow_call:

jobs:
  release-backend:
    name: Release Backend Server
    runs-on: ubuntu-22.04
    env:
      PROJECT_NAME: courserecom
      APP_NAME: backend
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Azure CLI Login
        uses: azure/login@v3
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID_TERRAFORM }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Backend to Container App
        uses: azure/cli@v3
        with:
          azcliversion: latest
          inlineScript: |
            az containerapp update \
              -n ca-${{ env.PROJECT_NAME }} \
              -g rg-${{ env.PROJECT_NAME }} \
              --image acr${{ env.PROJECT_NAME }}.azurecr.io/${{ env.APP_NAME }}:latest \
              --replace-env-vars \
                TIMESTAMP=$(date +%s) \
                MYSQL_DATABASE_NAME=secretref:mysql-database-name \
                MYSQL_URL=secretref:mysql-url \
                MYSQL_USERNAME=secretref:mysql-username \
                MYSQL_ROOT_PASSWORD=secretref:mysql-root-password \
                MYSQL_PORT=3306 \
                JWT_EXPIRATION=99999999999 \
                FRONTEND_URL=https://www.courserecom.site
